spring:
  datasource:
    url: jdbc:mysql://localhost:3307/department_db
    username: developer
    password: test1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8086
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
message: "Hello World From GIT"