spring:
#  application:
#    name: first-service
#  config:
#    import: configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"

message: "Hello World"
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/department_db
#    username: developer
#    password: test1234
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1 # Replace with the correct IP address
#    hostname: 127.0.0.1
#message: "Hello World From GIT"
